[package]
name = "coin-flip"
version = "0.1.0"
edition = "2021"


[dependencies]
cosmwasm-std = "1.1"
cw-storage-plus = "1.1.0"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }